# Generated by Django 4.0 on 2022-09-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='temp',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
